version: '4.5'

services:
  application:
    image: application:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/application
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: data
    ports:
      - "5432:5432"
#    depends_on:
#      - prometheus
#
#  prometheus:
#      image: prom/prometheus:latest
#      volumes:
#        - ./prometheus.yml
#      ports:
#        - 9090:9090

#  grafana:
#      image: grafana/grafana:latest
#      depends_on:
#        - prometheus
#      ports:
#        - "3000:3000"
#      volumes:
#        - ./grafana #:/etc/grafana/





